version: '3'
services:
  redis:
    # 镜像名称以及版本号
    image: redis:latest
    # 失败后总是重启
    restart: always
    # 自定义容器名
    container_name: docker_redis
    # 文件夹以及文件映射
    volumes:
      - ${HOME}/app/redis/datadir:/data
      # 需要先新建redis.conf文件
      - ${HOME}/app/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ${HOME}/app/redis/logs:/logs
    command:
    # 以配置文件的方式启动
      redis-server /usr/local/etc/redis/redis.conf
    ports:
    # 端口号
      - '6379:6379'
  db:
    image: mysql:8.0.32
    restart: always
    container_name: docker_mysql
    command: --default-authentication-plugin=mysql_native_password 
    environment:
      MYSQL_ROOT_PASSWORD: han123
    ports:
      - 3306:3306
    volumes:
      - ${HOME}/app/mysql/data:/var/lib/mysql
      - ${HOME}/app/mysql/config:/etc/mysql/conf.d